# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='from_node_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='to_node_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
