# Generated by Django 2.0.3 on 2018-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='simulation_info',
            field=models.TextField(default='null'),
        ),
    ]
