# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('model', 'device_number', 'device_type')]),
        ),
    ]
