# -*- coding: utf-8 -*-

type_table = {
-2:  'Undefined device type.',
-1:  'All devices type.',
0:   'Regulator type.',
1:   'Transformer type.',
2:   'Breaker type.',
3:   'LVCB type.',
4:   'Recloser type.',
5:   'Sectionalizer type.',
6:   'Switch type.',
7:   'Fuse type.',
8:   'Series Capacitor type.',
9:   'Series Reactor type.',
10:  'Underground type.',
11:  'Overhead Line type.',
13:  'Overhead By Phase type.',
14:  'Spot Load type.',
15:  'Distributed Load type.',
16:  'Shunt Capacitor type.',
17:  'Shunt Reactor type.',
18:  'Miscellaneous type.',
19:  'Arc Furnace type.',
20:  'CType Filter type.',
21:  'Double Tuned Filter type.',
22:  'High Pass Filter type.',
23:  'Ideal Converter type.',
24:  'Non Ideal Converter type.',
25:  'Shunt Frequency Source type.',
26:  'Series Frequency Source type.',
27:  'Single Tuned Filter type.',
28:  'Induction Generator type.',
29:  'Synchronous Generator type.',
30:  'Induction Motor type.',
31:  'Synchronous Motor type.',
32:  'Three-Winding Transformer type.',
33:  'Transformer By Phase type.',
34:  'Electronic Converter Generator type.',
35:  'Source type.',
36:  'Network Equivalent type.',
37:  'Wind Energy Conversion System type (WECS).',
38:  'Grounding Transformer type.',
39:  'Photovoltaic type (PV).',
40:  'Micro Turbine type.',
41:  'Solid Oxide Fuel Cell type (SOFC).',
42:  'Auto Transformer type.',
43:  'Three-Winding Auto Transformer type.',
44:  'Static VAR compensator type (SVC).',
45:  'Shunt-Parallel RLC Branch type.',
46:  'Shunt RLC Branch type.',
47:  'Series Parallel RLC Branch type.',
48:  'Series RLC Branch type.',
49:  'Shunt Frequency Dependent Branch type.',
50:  'Series Frequency Dependent Branch type.',
51:  'Shunt Mutually Coupled 3-phases Branch type.',
52:  'Series Mutually Coupled 3-phases Branch type.',
53:  'Network Protector type.',
54:  'Busway type.',
55:  'Unified Power Flow Controller type (UPFC).',
56:  'Phase Shifter Transformer type.',
57:  'Static Synchronous Compensator type (STATCOM).',
58:  'Switchable Shunt Bank type.',
59:  'Dc Link type.',
60:  'Variable Frequency Drive type.',
61:  'Regulator By Phase type.',
62:  'Double Circuit Line type.',
63:  'Charger type.',
64:  'Damage Control Unit Patrol Station type (DCUPS).',
65:  'DC Motor type.',
66:  'Battery type.',
67:  'DC-DC Converter type.',
68:  'DC Cable type.',
69:  'DC Load type.',
70:  'DC Impedance type.',
71:  'DC Low Voltage Circuit Breaker type (DCLVCB).',
72:  'DC Fuse type.',
73:  'DC Switch type.'}