# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('task_id', models.CharField(blank=True, max_length=70)),
                ('status', models.CharField(default='NeedSim', max_length=10)),
                ('settings', models.TextField(default='null')),
                ('results', models.TextField(default='null')),
            ],
        ),
    ]
