# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
