# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.TextField(default='null'),
        ),
    ]
