# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='ConfigNeeded', max_length=20),
        ),
    ]
