# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='NeedSim', max_length=10),
        ),
    ]
