# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_models', '0002_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='load',
        ),
        migrations.AddField(
            model_name='load',
            name='SpotKWA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='SpotKWB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='SpotKWC',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
