# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_models', '0003_auto_20171115_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(),
        ),
    ]
