set MATLAB=C:\Program Files (x86)\MATLAB\R2011b
make -f compilation_1_sm_computation.mk  GENERATE_REPORT=0 EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0
